### ISSUE TITLE
Project which uses latest Microsoft.CodeAnalysis causes error Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.7.0.0

### ISSUE THREAD

**Issue by AdaskoTheBeAsT** [VerifyTests/Verify.SourceGenerators#268]
#### Describe the bug

When I try to launch debug on source generator and invoke

"""csharp
[ModuleInitializer]
public static void Init()
{
    VerifySourceGenerators.Initialize();
}
"""
I receive error

"""cmd
The type initializer for '<Module>' threw an exception.
   at System.RuntimeTypeHandle.GetActivationInfo(RuntimeType rt, & pfnAllocator, Void*& vAllocatorFirstArg, & pfnCtor, Boolean& ctorIsPublic)
   at System.RuntimeType.ActivatorCache..ctor(RuntimeType rt)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at ReflectionAbstractionExtensions.<>c__DisplayClass0_0.<CreateTestClass>b__0() in /_/src/xunit.execution/Extensions/ReflectionAbstractionExtensions.cs:line 42
   at Xunit.Sdk.ExecutionTimer.Aggregate(Action action) in /_/src/xunit.execution/Sdk/Frameworks/ExecutionTimer.cs:line 31
   at ReflectionAbstractionExtensions.CreateTestClass(ITest test, Type testClassType, Object[] constructorArguments, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource) in /_/src/xunit.execution/Extensions/ReflectionAbstractionExtensions.cs:line 42
   at Xunit.Sdk.TestInvoker`1.CreateTestClass() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 122
   at Xunit.Sdk.TestInvoker`1.<RunAsync>b__45_0() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 161
   at Xunit.Sdk.ExceptionAggregator.RunAsync[T](Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 107

System.IO.FileNotFoundException
Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Nie można odnaleźć określonego pliku.
   at VerifyTests.VerifySourceGenerators.Initialize()
   at AdaskoTheBeAsT.Identity.Dapper.SqlServer.Test.ModuleInitializer.Init() in C:\GitHub\AdaskoTheBeAsT.Identity.Dapper\test\unit\AdaskoTheBeAsT.Identity.Dapper.SqlServer.Test\ModuleInitializer.cs:line 10
   at .cctor()
"""

It looks like this project references old version of metapackage - could it be updated to last version please?

#### Minimal Repro

It is available [here](https://github.com/AdaskoTheBeAsT/AdaskoTheBeAsT.Identity.Dapper)

#### Submit a PR that fixes the bug

Submit a [Pull Request (PR)](https://help.github.com/articles/about-pull-requests/) that fixes the bug. Include in this PR a test that verifies the fix. If you were not able to fix the bug, a PR that illustrates your partial progress will suffice.

**Comment by SimonCropp** [comment]
can you share a **Minimal** Repro. ie the smallest possible codebase that reproduces the problem

**Comment by SimonCropp** [comment]
can u try version 2.3.0

and what versionf of VS are you using.

**Comment by AdaskoTheBeAsT** [comment]
Hi,

I am using VS 2022 Pro v.17.10.5

unfortunately on nuget there is only version 2.2.0

![image](https://github.com/user-attachments/assets/02f809ca-65e4-4b06-ae45-54607ff22af2)


Error which I receive

![image](https://github.com/user-attachments/assets/c3adf45c-a48e-4a7e-9b32-9bdeeb8d7f52)

Link to repro [https://github.com/AdaskoTheBeAsT/AdaskoTheBeAsT.Identity.Dapper](https://github.com/AdaskoTheBeAsT/AdaskoTheBeAsT.Identity.Dapper)

**Comment by SimonCropp** [comment]
can u try nuget again

**Comment by AdaskoTheBeAsT** [comment]
no - code analysis on version 4.9 also does not work

![image](https://github.com/user-attachments/assets/b93c7620-9ecf-4da3-af6a-36da48c5ccac)

**Comment by SimonCropp** [comment]
in that case i dont know.

any progress on a minimal repro? and pointing to you entire codebase is not minimal

**Comment by AdaskoTheBeAsT** [comment]
I think that problem is here but is here - I will prepare some minimal repro - anyway it does not change the fact that lib is dependant on Microsoft analysis 4.9.0

![image](https://github.com/user-attachments/assets/067aa1e8-af66-4a33-b79e-61b5ceaca22a)

**Comment by AdaskoTheBeAsT** [comment]
hi

minimal sample available here
https://github.com/AdaskoTheBeAsT/VerifySourceGeneratorCodeAnalysisIssue

when I use latest analyzers build just fails

when i switch off analyzers and downgrade to 4.9.2 as it is in branch

https://github.com/AdaskoTheBeAsT/VerifySourceGeneratorCodeAnalysisIssue/blob/feature/without-analyzers/SampleGenerator/SampleGenerator.csproj

all works

I think this is due to verify using older version of Microsoft.CodeAnalysis.CSharp

https://github.com/VerifyTests/Verify.SourceGenerators/blob/17b88972262956ce7dd8d02e9a360a3107f51067/src/Directory.Packages.props#L9

**Comment by SimonCropp** [comment]
try removing the `PrivateAssets="all" ExcludeAssets="runtime" ` from the following in your dir props

```

    <PackageReference Include="Microsoft.CodeAnalysis" Version="4.11.0"  />
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.4" />
    <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="4.11.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.11.0" />
```

**Comment by distantcam** [comment]
The package `AdaskoTheBeAsT.Puma.Security.Rules.2022` is also forcing a reference to `Microsoft.CodeAnalysis`

![image](https://github.com/user-attachments/assets/5e393099-49bc-4600-b218-d112cbf6f4ae)

**Comment by SimonCropp** [comment]
the problem is you have `PrivateAssets="all" ExcludeAssets="runtime" ` for the CodeAnalysis packages. which means they dont get copied to the output directory of the tests

**Comment by AdaskoTheBeAsT** [comment]
ok I see - thanks a lot!

**Comment by SimonCropp** [comment]
and fwiw, a repro that has 40+ package references is not minimal

**Comment by AdaskoTheBeAsT** [comment]
y I know - anyway I am obsessed with usage of source code analyzers
